spring:
  application:
    name: jnmap
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080
  servlet:
    context-path: jnmap

