server:
    port: 8443
    servlet:
        context-path: /jnmap
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: 123456
        keyStoreType: PKCS12
        keyAlias: myalias

http:
    port: 8090

spring:
    application:
        name: jnmap
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            max-request-size: 500MB

    datasource:
        druid:
#            driverClassName: com.mysql.jdbc.Driver
#            url:  jdbc:mysql://localhost:3306/jnmap?useUnicode=true&characterEncoding=utf8&useSSL=false
#            username: root
#            password: ayufan
            driverClassName: org.h2.Driver
            url:  jdbc:h2:${user.dir}/h2/jnmap
            username: root
            password: ayufan
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000                                # 获取连接的超时等待时间
            timeBetweenEvictionRunsMillis: 60000          # 检查要关闭的空闲连接
            min-evictableIdleTimeMillis: 30000            # 连接空闲多久后关闭
            validationQuery: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true

        schema: classpath:sql/schema.sql                  # 初始化schema的SQL

    # config for access to static resources
    resources:
        static-locations: classpath:/static
    mvc:
        static-path-pattern: /static/**

freemarker:
    content-type: text/html
    charset: utf-8

mybatis:
    mapper-locations: classpath:mapxml/*.xml
    type-aliases-package: com.jia.jnmap.entity
    type-handlers-package: com.jia.jnmap.nmap.mybatis
